server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Ecommers
    username: root
    password: root
  endpoints:
    web:
      exposure:
        include: '*'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:1111/

auth-servies:
  messages:
    userReg: "User created"
    userRegErr: "User creation failed"
    login: "Login success"
    loginErr: "Invalid details please check username and password"
