server:
  port: 8081
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/Ecommers
    username: root
    management:
  endpoints:
    web:
      exposure:
        include: '*'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    boot:
    admin:
      client:
        url:http://localhost:1111/
        
